# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: shihab.suliman@diamond.ac.uk
author_name: Shihab Suliman
component_owner: user:rye74444
description: webcontrol
distribution_name: PandABlocks-webcontrol
docker: true
docs_type: README
git_platform: github.com
github_org: PandABlocks
package_name: pandablocks
pypi: false
repo_name: PandABlocks-webcontrol
type_checker: pyright
